/*
SQLyog Community Edition- MySQL GUI v8.14 
MySQL - 5.1.37-1ubuntu5 : Database - asteriskcti
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`asteriskcti` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `asteriskcti`;

/*Table structure for table `actions` */

DROP TABLE IF EXISTS `actions`;

CREATE TABLE `actions` (
  `ID_ACTION` bigint(20) NOT NULL AUTO_INCREMENT,
  `ACTION_OS_TYPE` enum('ALL','LINUX','MACINTOSH','WINDOWS') DEFAULT 'ALL',
  `ACTION_TYPE` enum('APPLICATION','BROWSER','INTERNAL_BROWSER','TCP_MESSAGE','UDP_MESSAGE') DEFAULT NULL,
  `ACTION_DESTINATION` varchar(255) DEFAULT NULL,
  `PARAMETERS` text,
  `ENCODING` enum('UTF8','ISO-8859-1','ISO-8859-15') DEFAULT NULL,
  PRIMARY KEY (`ID_ACTION`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;

/*Table structure for table `dbversion` */

DROP TABLE IF EXISTS `dbversion`;

CREATE TABLE `dbversion` (
  `VERSION` double DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;

/*Table structure for table `operators` */

DROP TABLE IF EXISTS `operators`;

CREATE TABLE `operators` (
  `ID_OPERATOR` bigint(20) NOT NULL AUTO_INCREMENT,
  `FULL_NAME` varchar(100) NOT NULL,
  `USERNAME` varchar(100) NOT NULL,
  `PASS_WORD` varchar(32) NOT NULL,
  `LAST_SEAT` bigint(20) DEFAULT NULL,
  `BEGIN_IN_PAUSE` tinyint(1) DEFAULT '0',
  `ENABLED` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`ID_OPERATOR`),
  UNIQUE KEY `USERNAME` (`USERNAME`),
  KEY `FK_seat_operator` (`LAST_SEAT`),
  CONSTRAINT `FK_seat_operator` FOREIGN KEY (`LAST_SEAT`) REFERENCES `seats` (`ID_SEAT`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;

/*Table structure for table `seats` */

DROP TABLE IF EXISTS `seats`;

CREATE TABLE `seats` (
  `ID_SEAT` bigint(20) NOT NULL AUTO_INCREMENT,
  `SEAT_MAC` varchar(17) NOT NULL DEFAULT '00:00:00:00:00:00',
  `SEAT_EXTEN` varchar(50) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID_SEAT`),
  UNIQUE KEY `SEAT_MAC` (`SEAT_MAC`),
  UNIQUE KEY `SEAT_EXTEN` (`SEAT_EXTEN`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;

/*Table structure for table `server_settings` */

DROP TABLE IF EXISTS `server_settings`;

CREATE TABLE `server_settings` (
  `name` varchar(128) NOT NULL,
  `val` longtext NOT NULL,
  PRIMARY KEY (`name`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;

/*Table structure for table `services` */

DROP TABLE IF EXISTS `services`;

CREATE TABLE `services` (
  `ID_SERVICE` bigint(20) NOT NULL AUTO_INCREMENT,
  `SERVICE_NAME` varchar(100) DEFAULT NULL,
  `SERVICE_CONTEXT_TYPE` enum('INBOUND','OUTBOUND') DEFAULT 'INBOUND',
  `SERVICE_IS_QUEUE` tinyint(1) DEFAULT '0',
  `SERVICE_QUEUE_NAME` varchar(100) DEFAULT NULL,
  `ENABLED` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`ID_SERVICE`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;

/*Table structure for table `services_actions` */

DROP TABLE IF EXISTS `services_actions`;

CREATE TABLE `services_actions` (
  `ID_SERVICE` bigint(20) DEFAULT NULL,
  `ID_ACTION` bigint(20) DEFAULT NULL,
  `ACTION_ORDER` tinyint(4) DEFAULT NULL,
  UNIQUE KEY `UniqueServiceAction` (`ID_SERVICE`,`ID_ACTION`),
  KEY `FK_actions` (`ID_ACTION`),
  CONSTRAINT `FK_actions` FOREIGN KEY (`ID_ACTION`) REFERENCES `actions` (`ID_ACTION`) ON DELETE CASCADE,
  CONSTRAINT `FK_services` FOREIGN KEY (`ID_SERVICE`) REFERENCES `services` (`ID_SERVICE`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;

/*Table structure for table `services_operators` */

DROP TABLE IF EXISTS `services_operators`;

CREATE TABLE `services_operators` (
  `ID_SERVICE` bigint(20) NOT NULL,
  `ID_OPERATOR` bigint(20) NOT NULL,
  `PENALTY` int(11) DEFAULT '0',
  UNIQUE KEY `ID_SERVICE` (`ID_SERVICE`,`ID_OPERATOR`),
  KEY `FK_operators_services` (`ID_OPERATOR`),
  CONSTRAINT `FK_operators_services` FOREIGN KEY (`ID_OPERATOR`) REFERENCES `operators` (`ID_OPERATOR`) ON DELETE CASCADE,
  CONSTRAINT `FK_services_operators` FOREIGN KEY (`ID_SERVICE`) REFERENCES `services` (`ID_SERVICE`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;

/*Table structure for table `services_variables` */

DROP TABLE IF EXISTS `services_variables`;

CREATE TABLE `services_variables` (
  `ID_VARIABLE` bigint(20) NOT NULL AUTO_INCREMENT,
  `ID_SERVICE` bigint(20) NOT NULL,
  `VARNAME` varchar(100) NOT NULL,
  PRIMARY KEY (`ID_VARIABLE`),
  UNIQUE KEY `SERVICE_VARNAME` (`ID_SERVICE`,`VARNAME`),
  CONSTRAINT `FK_services_variables` FOREIGN KEY (`ID_SERVICE`) REFERENCES `services` (`ID_SERVICE`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
